//
//  Variation.swift
//  MetaCocktailsSwiftData
//
//  Created by Matt Hunt on 2/15/24.
//

import Foundation

enum Variation: String, Codable, CaseIterable {
    
    
    case airMail = "Air Mail"
    case alaska = "Alaska"
    case algonquin = "Algonquin"
    case amarettoSour = "Amaretto Sour"
    case americano = "Americano"
    case appleJackCocktail = "Apple Jack Cocktail"
    case beesKnees = "Bees Knees"
    case betweenTheSheets = "Between the Sheets"
    case bamboo = "Bamboo"
    case bijou = "Bijou"
    case bloodAndSand = "Blood & Sand"
    case bloodyMary = "Bloody Marry"
    case boulevardier = "Boulevardier"
    case bramble = "Bramble"
    case brandyCrusta = "Brandy Crusta"
    case brownDerby = "Brown Derby"
    case brooklyn = "Brooklyn"
    case cloverClub = "Clover Club"
    case corpseReviver = "Corpse Reviver"
    case daiquiri = "Daiquiri"
    case elPresidente = "El Presidente"
    case fairAndWarmer = "Fair and Warmer"
    case fancyFree = "Fancy Free"
    case featheredHatFlip = "Feathered Hat Flip"
    case fogCutter = "Fog Cutter"
    case french75 = "French 75"
    case ginFizz = "Gin Fizz"
    case grasshopper = "Grasshopper"
    case greenpoint = "Greenpoint"
    case hankyPanky = "Hanky Panky"
    case harveyWallbanger = "Harvey Wallbanger"
    case homeOnTheRange = "Home on the Range"
    case honeymoon = "Honeymoon Cocktail"
    case hollandHouse = "Holland House"
    case hotelNacional = "Hotel Nacional"
    case hotToddy = "Hot Toddy"
    case hurricane = "Hurricane"
    case irishCoffee = "Irish Coffee"
    case japanese = "Japanese Cocktail"
    case jungleBird = "Jungle Bird"
    case kentuckyMaid = "Kentucky Maid"
    case kirRoyale = "Kir Royale"
    case laLouisiane = "La Louisiane"
    case lastWord = "Last Word"
    case lemonDrop = "Lemon Drop"
    case maiTai = "Mai Tai"
    case majorBailey = "Major Bailey"
    case margarita = "Margarita"
    case martinez = "Martinez"
    case martini = "Martini"
    case mexicanFiringSquad = "Mexican Firing Squad"
    case mintJulep = "Mint Julep"
    case modernCocktail = "Modern Cocktail"
    case mojito = "Mojito"
    case morningGloryFizz = "Morning Glory Fizz"
    case newYorkSour = "New York Sour"
    case oaxacaOldFashioned = "Oaxaca Old Fashioned"
    case oldFashioned = "Old Fashioned"
    case oldCuban = "Old Cuban"
    case oldPal = "Old Pal"
    case painKiller = "Pain Killer"
    case penicillin = "Penicillin"
    case piscoSour = "Pisco Sour"
    case queensParkSwizzle = "Queens Park Swizzle"
    case rememberTheMaine = "Remember The Maine"
    case robRoy = "Rob Roy"
    case saturn = "Saturn"
    case sazerac = "Sazerac"
    case scofflaw = "Scofflaw"
    case sherryCobbler = "Sherry Cobbler"
    case sidecar = "Sidecar"
    case singaporeSling = "Singapore Sling"
    case sloeGinFizz = "Sloe Gin Fizz"
    case tiPunch = "Ti Punch"
    case tipperary = "Tipperary"
    case tomCollins = "Tom Collins"
    case ultimaPalabra = "Ultima Palabra"
    case vesper = "Vesper"
    case zombie = "Zombie"
}

